name: FoPzlVote
main: me.fopzl.vote.bukkit.BukkitVote
author: [FoPzl, Neoblade298]
depend: [NeoCore]
softdepend: [Votifier]
version: 1.0
api-version: 1.19
commands:
   vote:
      usage: "§cUsage: §7/<command>"
      permission: mlvote.general
   adminvote:
      aliases: [av]
      usage: "§cUsage: §7/<command>"
      permission: mlvote.general
permissions:
   mlvote.general:
      description: "General permission"
   mlvote.admin:
      description: "For admin functions like freevote"